name: terapiya_center
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  flutter_spinkit: ^5.2.1
  video_player: ^2.9.2
  table_calendar: ^3.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1
  http: ^1.3.0
  flutter_native_splash: ^2.4.4
  flutter_stripe: ^11.4.0
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  uuid: ^4.5.1
  pdf: ^3.11.3
  share_plus: ^10.1.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/slide/
    - assets/formations/
    - assets/board/
    - assets/board/formation.png
    - assets/board/don.png
    - assets/board/historique.png
    - assets/board/generaux.png
    - assets/board/personel.png
    - assets/board/contact.png
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash.png"
  android_12:
    image: "assets/splash.png"