// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqLA7qErKVpGkp706b4xD9BdX010DlCtg',
    appId: '1:210145337925:web:4511d9d391d8b45d45b92c',
    messagingSenderId: '210145337925',
    projectId: 'terpaiyacenter',
    authDomain: 'terpaiyacenter.firebaseapp.com',
    storageBucket: 'terpaiyacenter.firebasestorage.app',
    measurementId: 'G-LY4GL4S69R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxg8RM22OmkDmS0Ae68gEzjiNsbK15U0c',
    appId: '1:210145337925:android:e1ab7e43feefe12345b92c',
    messagingSenderId: '210145337925',
    projectId: 'terpaiyacenter',
    storageBucket: 'terpaiyacenter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC04pHkYlnKuH1Y7wjUaE3FxIDlbwhNZ-4',
    appId: '1:210145337925:ios:ed08398a5ca01a5645b92c',
    messagingSenderId: '210145337925',
    projectId: 'terpaiyacenter',
    storageBucket: 'terpaiyacenter.firebasestorage.app',
    iosBundleId: 'com.example.terapiyaCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC04pHkYlnKuH1Y7wjUaE3FxIDlbwhNZ-4',
    appId: '1:210145337925:ios:ed08398a5ca01a5645b92c',
    messagingSenderId: '210145337925',
    projectId: 'terpaiyacenter',
    storageBucket: 'terpaiyacenter.firebasestorage.app',
    iosBundleId: 'com.example.terapiyaCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqLA7qErKVpGkp706b4xD9BdX010DlCtg',
    appId: '1:210145337925:web:e9389ab83a27af3945b92c',
    messagingSenderId: '210145337925',
    projectId: 'terpaiyacenter',
    authDomain: 'terpaiyacenter.firebaseapp.com',
    storageBucket: 'terpaiyacenter.firebasestorage.app',
    measurementId: 'G-CZKE2GD81Z',
  );

}