// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0YZRA-Cqvy0f5YTtEvYPHale9f-H_DQM',
    appId: '1:731330200988:web:e94dfae5bfd8c66ce27459',
    messagingSenderId: '731330200988',
    projectId: 'terapiya-8b8ff',
    authDomain: 'terapiya-8b8ff.firebaseapp.com',
    storageBucket: 'terapiya-8b8ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf5tXcaHhoR5EO5iLBvv0Kfm1UQQ2Cq5Y',
    appId: '1:731330200988:android:03630d4f3f77d61de27459',
    messagingSenderId: '731330200988',
    projectId: 'terapiya-8b8ff',
    storageBucket: 'terapiya-8b8ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9vzuarnJ4cI4KQF4GeDW5sJgueExXG38',
    appId: '1:731330200988:ios:87b7c54658d6cdcce27459',
    messagingSenderId: '731330200988',
    projectId: 'terapiya-8b8ff',
    storageBucket: 'terapiya-8b8ff.firebasestorage.app',
    iosBundleId: 'com.example.terapiyaCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9vzuarnJ4cI4KQF4GeDW5sJgueExXG38',
    appId: '1:731330200988:ios:87b7c54658d6cdcce27459',
    messagingSenderId: '731330200988',
    projectId: 'terapiya-8b8ff',
    storageBucket: 'terapiya-8b8ff.firebasestorage.app',
    iosBundleId: 'com.example.terapiyaCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0YZRA-Cqvy0f5YTtEvYPHale9f-H_DQM',
    appId: '1:731330200988:web:1a1b0deb0ddcb9e6e27459',
    messagingSenderId: '731330200988',
    projectId: 'terapiya-8b8ff',
    authDomain: 'terapiya-8b8ff.firebaseapp.com',
    storageBucket: 'terapiya-8b8ff.firebasestorage.app',
  );
}
